// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShiftsLogger.WebAPI.davetn657.Data;

#nullable disable

namespace ShiftsLogger.WebAPI.davetn657.Data.Migrations
{
    [DbContext(typeof(ShiftsLoggerDbContext))]
    [Migration("20260317120707_TimespanNullable")]
    partial class TimespanNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("ShiftsLogger.WebAPI.davetn657.Data.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoggerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ShiftEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ShiftStart")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Shifts");
                });
#pragma warning restore 612, 618
        }
    }
}
